brokers:
  hosts:
    broker:
      ansible_host: 127.0.0.1
      ansible_user: vagrant
      ansible_port: 2200
      ansible_ssh_private_key_file: ./.vagrant/machines/broker/virtualbox/private_key
    

