- hosts: brokers
  become: yes

  pre_tasks:
    - name: Upgrade
      apt:
        update_cache: yes
        install_recommends: yes

    - name: Install java 17 JRE
      apt:
        pkg:
          - curl
          - openjdk-17-jre

    - name: See if kafka is downloaded
      stat:
        path: /usr/bin/kafka/LICENSE
      register: kafka_download

    - name: Download kafka
      shell: |
        mkdir ~/Downloads
        curl "https://dlcdn.apache.org/kafka/4.0.0/kafka_2.13-4.0.0.tgz" -o ~/Downloads/kafka.tgz
        sudo mkdir /usr/bin/kafka
        sudo tar -xvzf ~/Downloads/kafka.tgz -C /usr/bin/kafka --strip 1
      when: kafka_download.stat.exists == False

    - name: Configure kafka
      shell: |
        cd /usr/bin/kafka
        KAFKA_CLUSTER_ID="$(bin/kafka-storage.sh random-uuid)"
        bin/kafka-storage.sh format --standalone -t $KAFKA_CLUSTER_ID -c config/server.properties

    - name: Copy kafka.service
      copy:
        src: kafka.service
        dest: /lib/systemd/system/kafka.service

    - name: Reload system config
      shell: systemctl daemon-reload

  tasks:
    - name: start kafka service daemon
      systemd:
        name: kafka.service
        enabled: true
        state: started

    - name: Create topic
      shell: |
        /usr/bin/kafka/bin/kafka-topics.sh --create --topic test-events --bootstrap-server localhost:9092
